In [45]:
import numpy as np

class Perceptron(object):
    def __init__(self, input_size, lr = 1, epochs = 10):
        self.W = np.zeros(input_size + 1)
        #add one for bias
        self.epochs = epochs
        self.lr = lr
        
    def activation_fn(self, x):
        return 1 if x >= 0 else 0
    
    def predict(self,x):
        x = np.insert(x, 0, 1)
        z = self.W.T.dot(x)
        a = self.activation_fn(z)
        return a
    
    def fit(self, X, d):
        for _ in range (self.epochs):
            for i in range(d.shape[0]):
                y = self.predict(X[i])
                e = d[i] - y
                self.W = self.W + self.lr * e * np.insert(X[i], 0, 1)
                
# __init__ fonksiyonu yapıcı fonksiyondur. Perceptron sınıfından bir obje oluşturulurken çağırılır ve kendisine verilen
# değerlerle atama işlemi yapar.
# activation_fn fonksiyonu ise değerin işaretine göre 1 yada 0 geri gönderen bir fonksiyondur.
# predict fonksiyonu ise kendisine gönderilen dizinin tüm işlemleri sonucu hangi çıktıyı verdiğini gösteren fonksiyondur.
# fit fonksiyonu işlemler sonucu Perceptron sınıfının W değerlerini bulan fonksiyondur.

# XOR işlemi için değerler:
Xxor = np.array([
         [0,0],
         [0,1],
         [1,0],
         [1,1]
])

dxor = np.array([0, 1, 1, 0])

p1 = Perceptron(input_size = 2)
p1.fit(Xxor, dxor)
print(p1.W)

# 40 farklı imza olacağı için d değeri 40 farklı değer alabilir. X değeri için ise resimlerin 250*250 piksel olduğunu
# kabul edersek 250*250*3'ün tek bir sütun şeklinde sıralandığı bir veri setimiz olur. 

# Perceptron sınıfının fonksiyonu olan predict'ten geri dönen değeri o değerin çıkışı olan d değerinden çıkartırsak error
# hata değerini hesaplayabiliriz.

[ 0. -1.  0.]


In [39]:
X = np.array([
         [0,0],
         [0,1],
         [1,0],
         [1,1]
])

In [40]:
d = np.array([0,0,0,1])

In [43]:
perceptron = Perceptron(input_size = 2)

In [44]:
perceptron.fit(X, d)
print(perceptron.W)

[-3.  2.  1.]


In [9]:
mp.activation_fn(-10)

0

In [7]:
mp = Perceptron(5)

In [25]:
mp.W

array([0., 0., 0., 0., 0., 0.])